### ISSUE TITLE
Communicating: Where are we?

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/fossrit.github.io#4]
# Problem

When visiting the website, it's unclear how someone could remotely get in touch with other FOSS students on campus without coming to a meeting.
# Analysis

We want a clearly emphasized place of platforms that the FOSS@MAGIC program lives so it's easy for someone to check out the program and receive a response from the group. Currently, the best choices are [IRC](https://webchat.freenode.net/?channels=rit-foss) and the [FLOSS Seminar mailing list](https://lists.rit.edu/mailman/listinfo.mmcgi/floss-seminar) (not my favorite choices for on-boarding new students or keeping people involved, but…).

We could embed a webchat client similar to what you find [here](https://justinwflory.com/chat/) on my website, or we could redirect them to the normal webchat client from freenode. The mailing list should have steps for subscribing (including the common problem of `@g.rit.edu` vs. `@rit.edu`).

This accomplishes the purpose of:
1. Supporting existing program with more easily accessible info
2. Ensure longevity of program by clearly having steps to get involved
# Implementation
1. Add space towards bottom of page for "get involved" / "contact" info
2. Design with the idea of "click-and-go" to participating (making it easier for people to connect and stay in the loop without having to actively try to be in the loop)
3. Deploy!

**Comment by Nolski** [comment]
We could run a telegram channel?

**Comment by jflory7** [comment]
@Nolski I personally really like the idea of a Telegram group. Plus, with @repkam09's [super handy bot](https://github.com/RITlug/teleirc) we're using in #ritlug, it would be easy to introduce a relay between the two farther down the line.

Or do you mean like one of the announcement channels for news / updates??

**Comment by Nolski** [comment]
I'd say one just for chatting. To be totally honest I feel like the fossbox was always a more social group. Maybe keeping a catalog of current active projects and allowing people to contribute. Maybe a newsletter or something too? Before all of this info was distributed in a social setting when we had space but now it's difficult to maintain that constant communication without some heavy lifting on part of the students.

**Comment by jflory7** [comment]
@Nolski I would be +1 for a Telegram group. A newsletter would be ideal too (maybe something to aim for farther down the line). Are you on Telegram?

**Comment by jflory7** [comment]
For the time being, the Telegram thinger is living [here](https://telegram.me/fossrit). Consider it experimental for now…

**Comment by Nolski** [comment]
I am not on Telegram. Only IRC.

**Comment by ritjoe** [comment]
On Sat, Jan 14, 2017 at 05:46:37PM -0800, Mike Nolan wrote:
> I am not on Telegram. Only IRC.

sometimes via a matrix bridge too, right?

Me too.

Specifically, via an account on, and a connection to, the home server run by
the protocol lead developers at matrix.org.  I use the cross-platform app
found at riot.im/app on which they also lead development.

I'm using matrix/riot to participate in the IRC channel.

I also participate in the IRC channel via the IRC client irssi, running in
the terminal multiplexer tmux, hosted on a persistently Internet-connected
virtual private server (VPS) to which I connect via SSH.  This is a common
pattern for participating in IRC but imposes pretty severe demands for a
newcomer.

Ths pattern offers many options (IRC client options, SSH client options,
whether and how much to self-host or to use 3rd party hosts and services, to
run stand-alone services or to federate, whether or not to use bouncers and
how to configure them, whether to use VPS or a shared shell host as some of
the things that spring to mind).  Power users often delight in customizing
at least some components within the stack to suit their purposes, but
ultimately some consensus is required for it all to work together.

As with many complex toolchains, I think the biggest determinant as to
whether it ends up being exclusionary versus being an aspirational goal for
newcomers is in how welcome we are with encouragement and support for those
who try to operate this way.  Conversations like this one, exploring and
documenting what we do, work to that latter goal.

With appropriate choice of software, using IRC or Matrix either separately
or in conjunction can be end-to-end free.  That is, one can choose free and
open source software for all of it: Servers, clients, and any supporting
infrastructure.  Unfortunately, this is not true for Telegram (the server
has not been freed) nor for many other things that otherwise would be
options (eg, Slack, Gitter, or myriad other social media platforms relying
either in part or in whole on proprietary software stacks). 

We should continue to welcome interested people via the freenode-supplied
IRC web client at http://webchat.freenode.net/?&channels=rit-foss We may
also find the mobile experience offered by a Matrix bridge to be more
"sticky", leading to better longer-term engagement since it more closely
matches how people stay in touch these days. Matrix take-up has been modest,
but as with all things its a question of how to build up to and maintain
critical mass. I've been late to the game. Much thanks to jflory and nolski
for leading the way with Matrix.

One thing I've been meaning to do is to try to figure out how to document
and give notice of the fact that the Matrix integration (and probably the
Telegram integration) leads to their being a de facto public log of the
channel.  Some IRC channels are logged, some aren't, but it's a
widely-respected norm that channels that publically log traffic to the
channel should inform participants of such fact, so that each person can
moderate their behavior as they feel appropriate for a public venue.

For now, I might drop a link to this issue into the #rit-foss topic.

**Comment by jflory7** [comment]
In retrospect, this issue was intended to be a discussion about web design for the fossr.it website – for discussion about where we actually hold our discussions, at least for the mailing list, we should probably use [fossbox-tasks#30](https://github.com/FOSSRIT/fossbox-tasks/issues/30). Even though we started having meta conversations about it early in comments, we may want to split this out into a longer discussion in that repo if needed.
