### ISSUE TITLE
FOSS Hours day-of-week is incorrect for Fall 2019.

### ISSUE THREAD

**Issue by ritjoe** [FOSSRIT/fossrit.github.io#78]
Review needed for #77 for this please. Should be straightforward.

**Comment by jwflory** [comment]
#77 merged, thanks @ritjoe!

For what it's worth, while I appreciate you opening issues to track work done, I don't think it is necessary to open an issue after making a PR. The purpose of an issue is to provide a place for discussion _before_ a change happens; since you already have made a PR, we should use the PR as place for feedback and discussion. Does this feedback make sense?

Anyways, closing this as complete. :clapper:

**Comment by ritjoe** [comment]
tbh it's just that I could use the practice ;-)
